### ISSUE TITLE
Confusing Extra Words "....and out" Line 5 of Lesson

### ISSUE THREAD

**Issue by ccklight** [learn-co-curriculum/viewport#2]
Line 5 is confusing with the "ignore them AND OUT on your website?" See lesson text below.
********

Problem Statement
Have you ever visited a website on your phone where it will zoom out and everything on the page is very tiny--then you have to zoom in to read the text and see the content? Have you found yourself writing a lot of media queries to make your content scale, stretch, or fit on various sized screens, just to have the device itself ignore them and out on your website? How can we have control over these default features that mobile browsers enforce?

**Comment by Sdcrouse** [comment]
I am curious about this as well.

**Comment by jenmyers** [comment]
Resolved.
